added solution
mate-academy/jv-immutable pull request #107
Opened 2021-04-19 17:00 UTC by Anatolii-Zarytskyi

2021-04-19 17:47 UTC, Aalderaan requested changes

2021-04-19 17:47 UTC, Aalderaan commented on src/main/java/core/basesyntax/Car.java
> +    }
This  repeats two times, maybe it is good to create method, that check for null and clone engine?

2021-04-19 17:47 UTC, Aalderaan commented on src/main/java/core/basesyntax/Car.java
> +            clonedWheels.add(new Wheel(wheel.getRadius()));
Maybe It is possible to make it shorter - (similar is on line 46) by adding directly wheel.clon()?

2021-04-19 18:08 UTC, Anatolii-Zarytskyi commented on src/main/java/core/basesyntax/Car.java
> +    }
done

2021-04-19 18:09 UTC, Anatolii-Zarytskyi commented on src/main/java/core/basesyntax/Car.java
> +            clonedWheels.add(new Wheel(wheel.getRadius()));
Agree. Done.

2021-04-19 18:50 UTC, Aalderaan requested changes

2021-04-19 19:00 UTC, Aalderaan approved these changes

2021-04-20 07:13 UTC, RomanDubovskyi requested changes

2021-04-20 07:13 UTC, RomanDubovskyi commented on src/main/java/core/basesyntax/Car.java
> +    public Car clone() {
we don't need this method, besides it doesn't create deep copy now  - let's remove it

2021-04-20 07:13 UTC, RomanDubovskyi commented on src/main/java/core/basesyntax/Car.java
> +    private Engine checkAndCloneEngine(Engine engine) {
move this method near the public method where you use it or to the end of the file near to your second private method

2021-04-20 09:26 UTC, RomanDubovskyi approved these changes

2022-12-30 18:39 UTC, closed without merging