Solved the task
mate-academy/jv-immutable pull request #49
Opened 2020-12-21 13:58 UTC by Likh-Alex

- Implemented methods `changeEngine`, `changeColor`, `addWheel`
- Created methods `checkEngine` , `clonedWheels`

2020-12-21 15:26 UTC, Ketch92 requested changes

2020-12-21 15:26 UTC, Ketch92 commented on src/main/java/core/basesyntax/Car.java
> +    }
You can merge these two methods as they do the same thing

2020-12-21 15:26 UTC, Ketch92 commented on src/main/java/core/basesyntax/Car.java
> +    }
I think this method is redundant, you can use the ternary operator for such a small thing

2020-12-21 15:26 UTC, Ketch92 commented on src/main/java/core/basesyntax/Car.java
> +    }
Do you really need to clone here something?

2020-12-21 15:26 UTC, Ketch92 commented on src/main/java/core/basesyntax/Car.java
> +        return new Car(year, color, newWheels, engine.clone());
don't you have a separate method for cloning the wheels?

2020-12-21 15:51 UTC, Likh-Alex reviewed
accidental push of review

2020-12-21 15:52 UTC, Likh-Alex commented on src/main/java/core/basesyntax/Car.java
> +    }
Done, I agree - ternary operator is a clearer statement

2020-12-21 15:52 UTC, Likh-Alex commented on src/main/java/core/basesyntax/Car.java
> +    }
Nope, thank you for an idea of doubling the cloning)

2020-12-21 15:53 UTC, Likh-Alex commented on src/main/java/core/basesyntax/Car.java
> +        return new Car(year, color, newWheels, engine.clone());
Refactored the `addWheel` to work with `clonedWheels`

2020-12-21 16:01 UTC, Ketch92 approved these changes

2020-12-21 16:50 UTC, KseniiaMakarova requested changes

2020-12-21 16:50 UTC, KseniiaMakarova commented on src/main/java/core/basesyntax/Car.java
> +        this.engine = engine != null ? engine.clone() : null;
`engine != null ? engine.clone() : null;` let’s move this logic into the private method as well

2020-12-21 16:50 UTC, KseniiaMakarova commented on src/main/java/core/basesyntax/Car.java
> +    }
should we return deep copy here?

2020-12-21 16:50 UTC, KseniiaMakarova commented on src/main/java/core/basesyntax/Car.java
> +    private List<Wheel> clonedWheels(List<Wheel> wheels) {
```suggestion
    private List<Wheel> getClonedWheels(List<Wheel> wheels) {
```

2020-12-21 16:50 UTC, KseniiaMakarova commented on src/main/java/core/basesyntax/Car.java
> +            clonedWheels.add(wheel.clone());
what if `wheel == null`? let’s add `null` to the new list then

2020-12-21 16:50 UTC, KseniiaMakarova commented on src/main/java/core/basesyntax/Car.java
> +        }
let's use our constructor here instead

2020-12-21 17:32 UTC, Likh-Alex commented on src/main/java/core/basesyntax/Car.java
> +        this.engine = engine != null ? engine.clone() : null;
done, created `checkIfEngineNull` method

2020-12-21 17:32 UTC, Likh-Alex commented on src/main/java/core/basesyntax/Car.java
> +    }
done, initialising AL with `clonedWheels`

2020-12-21 17:32 UTC, Likh-Alex commented on src/main/java/core/basesyntax/Car.java
> +    private List<Wheel> clonedWheels(List<Wheel> wheels) {
Done

2020-12-21 17:33 UTC, Likh-Alex commented on src/main/java/core/basesyntax/Car.java
> +        }
simplified by returning new `Car` object

2020-12-21 17:33 UTC, Likh-Alex commented on src/main/java/core/basesyntax/Car.java
> +            clonedWheels.add(wheel.clone());
Done, if any of `wheel` is `null` --> adding as well

2020-12-22 09:23 UTC, KseniiaMakarova requested changes

2020-12-22 09:23 UTC, KseniiaMakarova commented on src/main/java/core/basesyntax/Car.java
> +            clonedWheels.add(wheel.clone());
line 48 is executed even if wheel == null

2020-12-22 09:23 UTC, KseniiaMakarova commented on src/main/java/core/basesyntax/Car.java
> +        return new ArrayList<>(getClonedWheels(wheels));
do you need to create `new ArrayList<>()` here?

also, let's move private method below the place where we call it

2020-12-22 09:23 UTC, KseniiaMakarova commented on src/main/java/core/basesyntax/Car.java
> +        return checkIfEngineNull(engine);
same here - move the private method below this call

2020-12-22 09:23 UTC, KseniiaMakarova commented on src/main/java/core/basesyntax/Car.java
> +    private Engine checkIfEngineNull(Engine engine) {
```suggestion
    private Engine cloneEngine(Engine engine) {
```

2020-12-22 09:23 UTC, KseniiaMakarova commented on src/main/java/core/basesyntax/Car.java
> +        return new Car(year, color, getClonedWheels(wheels), engine.clone());
do you need to pass clones to the constructor? what will happen in the constructor?

2020-12-22 09:35 UTC, Likh-Alex commented on src/main/java/core/basesyntax/Car.java
> +            clonedWheels.add(wheel.clone());
Added `else` block

2020-12-22 09:36 UTC, Likh-Alex commented on src/main/java/core/basesyntax/Car.java
> +        return new ArrayList<>(getClonedWheels(wheels));
refactored to return result of `getClonedWheels` itself

2020-12-22 09:36 UTC, Likh-Alex commented on src/main/java/core/basesyntax/Car.java
> +        return new ArrayList<>(getClonedWheels(wheels));
Moved related methods down below their callers

2020-12-22 09:36 UTC, Likh-Alex commented on src/main/java/core/basesyntax/Car.java
> +        return checkIfEngineNull(engine);
Done

2020-12-22 09:37 UTC, Likh-Alex commented on src/main/java/core/basesyntax/Car.java
> +    private Engine checkIfEngineNull(Engine engine) {
Done

2020-12-22 09:38 UTC, Likh-Alex commented on src/main/java/core/basesyntax/Car.java
> +        return new Car(year, color, getClonedWheels(wheels), engine.clone());
passing fields directly to the constructor instead of clones.

2020-12-22 10:43 UTC, KseniiaMakarova approved these changes

2022-12-21 21:28 UTC, closed without merging